### ISSUE TITLE
Import Modules

### ISSUE THREAD

**Issue by octal-laurence** [fusioncharts/react-fusioncharts-component#12]
Hi,
    I get console error sometimes.
"Uncaught TypeError: a.setChartData is not a function", as I observed this happens when the 3 module is about to regenerate on importing modules

import React from 'react';
import ReactDOM from 'react-dom';
import ReactFC from 'react-fusioncharts';
 
// Here import licensed version of FusionCharts
import FusionCharts from './path/to/fusioncharts';
import Charts from './path/to/fusioncharts/fusioncharts.charts';
 
// Provide FusionCharts core and other modules to resolve
ReactFC.fcRoot(FusionCharts, Charts)

, so my is this, although my page still running and execute the charts correctly even this error console showed, but there are times that it cause to break my page.

**Comment by ayanbhaduryfc** [comment]
Hi,

Sad to hear that you are facing this problem, please raise a ticket at support@fusioncharts.com with your licensing details so that we could assist you accordingly

**Comment by rohitkr** [comment]
Hi @octal-laurence 
We are unable to replicate the issue at our end. Would it be possible for you to share a scale-down sample?

**Comment by ashok1994** [comment]
Closing as no sample was provided, reopen with the scale down sample if the issue persists
