### ISSUE TITLE
JQuery question

### ISSUE THREAD

**Issue by mclarentgp** [fusioncharts/react-fusioncharts-component#5]
More of a question than an issue, but I noticed that JQuery is listed as a dependency in your package.json file.  Is this correct that the plugin and or fusion charts itself dependent on JQuery?  

I'm researching react charting packages right now for my react project and am looking to implement a charting tool thats not dependent on JQuery is why I am asking.

Thanks

**Comment by rohitkr** [comment]
@mclarentgp , Neither `react-fusioncharts` plugin  nor `FusionCharts` library is dependent on `jQuery`. In the `package.json` it was added for some internal samples (not available in this public repo). Will be removed from package.json in next release.
