### ISSUE TITLE
Production build error with fusioncharts.js 

### ISSUE THREAD

**Issue by proworkdev** [fusioncharts/react-fusioncharts-component#50]
"Uncaught SyntaxError: Function statements require a function name" on following files :
fusioncharts.js
fusioncharts/themes/fusioncharts.theme.iplans.js

**Comment by rohanoid5** [comment]
@proworkdev there is no theme file with name `iplans`. [These](https://www.fusioncharts.com/dev/themes/introduction-to-themes) are the list of available themes.
