### ISSUE TITLE
componentWillReceiveProps has been renamed in latest react 16.9.0

### ISSUE THREAD

**Issue by riyazpanarwala** [fusioncharts/react-fusioncharts-component#51]
![image](https://user-images.githubusercontent.com/35068273/63688931-49900b00-c826-11e9-90bb-4f159ca9d144.png)

In the future react release, componentWillReceiveProps will not work if it is not renamed or might be removed.
Can anyone please update the code as per new react version (16.9.0) ?

**Comment by rohanoid5** [comment]
Fixed in version [3.1.1](https://github.com/fusioncharts/react-fusioncharts-component/releases/tag/3.1.1)
