### ISSUE TITLE
Error trying to use licensed version....

### ISSUE THREAD

**Issue by CharGomez** [fusioncharts/react-fusioncharts-component#52]
What's the correct process to use upgrade to the Licensed version of Fusioncharts, I've tried to reference the js files from the downloaded folder, but I always get the same error....

`import FusionCharts from '../../assets/libs/fusioncharts/js/fusioncharts'`

<img width="1458" alt="index js -- fusioncharts 2019-09-01 18-42-22" src="https://user-images.githubusercontent.com/13445119/64084405-73df3e00-cce8-11e9-9114-1b8daa5bd857.png">

**Comment by ayanbhaduryfc** [comment]
could you please drop a mail to support@fusioncharts.com with your licensing details so that we could share the steps to apply the license on your react app

**Comment by CharGomez** [comment]
> could you please drop a mail to [support@fusioncharts.com](mailto:support@fusioncharts.com) with your licensing details so that we could share the steps to apply the license on your react app

Ok, sure sending the email right away...
