### ISSUE TITLE
Map collections are not auto download 

### ISSUE THREAD

**Issue by ankitkanojia** [fusioncharts/react-fusioncharts-component#53]
Need to implement MAP chart using fusion charts library but some how with npm package installer I can not able to download all map collection. rather I have to download those files from your official website and then need to paste in map folder. 

I tried 4-5 times but maps are not downloaded along with npm package.

Do we have any other way to handle this issue?

**Comment by siawo** [comment]
@ankitkanojia  Map definition files are available in npm as fusionmaps package. Please check https://www.npmjs.com/package/fusionmaps

**Comment by ankitkanojia** [comment]
@siawo thank you so much for sharing.
