### ISSUE TITLE
 chartMouseMove event is not getting fired in FusionTime React implementation

### ISSUE THREAD

**Issue by soumyasankarduttagit** [fusioncharts/react-fusioncharts-component#54]
chartMouseMove event is not getting fired in FusionTime React implementation whereas dataPlotClick event is getting fired.
Please check the following sample for chartMouseMove -> https://codesandbox.io/s/condescending-clarke-k5cm2
dataPlotClick -> https://codesandbox.io/s/kk732kl7vo

**Comment by siawo** [comment]
@soumyasdutta The event is working in the latest FusionCharts 3.15.1. Please refer to the below code.
`ReactFC.fcRoot(FusionCharts, Charts, TimeSeries, FusionTheme);

class ChartViewer extends React.Component {
  constructor(props) {
    super(props);
    const fusionTable = new FusionCharts.DataStore().createDataTable(
      data,
      schema
    );

    this.state = {
      inverted: false,
      type: 'timeseries',
      dataSource: {
        chart: {
          enableChartMouseMoveEvent: '1'
        },
        data: fusionTable
      }
    };
  }

  render() {
    return (
      <div>
        <ReactFC
          type={this.state.type}
          width={this.state.inverted ? '400' : '600'}
          height={this.state.inverted ? '600' : '400'}
          dataFormat="json"
          dataSource={this.state.dataSource}
          fcEvent-chartmousemove={() => console.log('here')}
        />
      </div>
    );
  }
}`
