### ISSUE TITLE
When there are two points with the same value, the label is overlapping each other

### ISSUE THREAD

**Issue by RodolfoE** [fusioncharts/react-fusioncharts-component#63]
here is an exemple showing the error
https://github.com/RodolfoE/errorOnReactFc 
![Capturar](https://user-images.githubusercontent.com/10153791/98405433-0bf25900-204b-11eb-855a-8e8a7c32e5c9.PNG)

**Comment by RodolfoE** [comment]
![Capturar](https://user-images.githubusercontent.com/10153791/98405942-db5eef00-204b-11eb-9573-a8daac9c7a2a.PNG)

**Comment by AyanBhadury** [comment]
@RodolfoE If you have two plots with almost similar values then the labels may overlap to resolve the problem use valuePosition attribute at the data level to fix the problem - http://jsfiddle.net/f0q2g1ue/

`  "data": [{
              "value": "15123",
              valuePosition:"ABOVE"
            }]`
