### ISSUE TITLE
overlappedcolumn2d chart throwing error in react js

### ISSUE THREAD

**Issue by DevadharshiniN** [fusioncharts/react-fusioncharts-component#64]
Overlappedcolumn2d chart  throws below error  while using it in react js:

> Uncaught SyntaxError: Unexpected token '<'
> fusioncharts.js:13 Uncaught (in promise) Error: ChunkLoadError: Loading chunk 12 failed.
> (missing: http://localhost:3000/fusioncharts.overlappedcolumn2d.js)
>     at Function.a.e (fusioncharts.js:13)
>     at d (fusioncharts.js:13)
>     at Function.<anonymous> (fusioncharts.js:13)
>     at i (fusioncharts.js:13)
>     at o (fusioncharts.js:13)
>     at h (fusioncharts.js:13)
>     at e.t.chartType (fusioncharts.js:13)
>     at new e (fusioncharts.js:13)
>     at new f (fusioncharts.js:13)
>     at ReactFC.renderChart (ReactFC.js:319)
>     at ReactFC.componentDidMount (ReactFC.js:78)
>     at commitLifeCycles (react-dom.development.js:20663)
>     at commitLayoutEffects (react-dom.development.js:23426)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
>     at invokeGuardedCallback (react-dom.development.js:4056)
>     at commitRootImpl (react-dom.development.js:23151)
>     at unstable_runWithPriority (scheduler.development.js:646)
>     at runWithPriority$1 (react-dom.development.js:11276)
>     at commitRoot (react-dom.development.js:22990)
>     at performSyncWorkOnRoot (react-dom.development.js:22329)
>     at react-dom.development.js:11327
>     at unstable_runWithPriority (scheduler.development.js:646)
>     at runWithPriority$1 (react-dom.development.js:11276)
>     at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
>     at flushSyncCallbackQueue (react-dom.development.js:11309)
>     at batchedEventUpdates$1 (react-dom.development.js:22403)
>     at batchedEventUpdates (react-dom.development.js:3745)
>     at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
>     at attemptToDispatchEvent (react-dom.development.js:6005)
>     at dispatchEvent (react-dom.development.js:5924)
>     at fusioncharts.js:13
> (anonymous) @ fusioncharts.js:13
> Promise.catch (async)
> Ne @ fusioncharts.js:13
> t._addChartDependency @ fusioncharts.js:13
> t.chartType @ fusioncharts.js:13
> e @ fusioncharts.js:13
> f @ fusioncharts.js:13
> renderChart @ ReactFC.js:319
> componentDidMount @ ReactFC.js:78
> commitLifeCycles @ react-dom.development.js:20663
> commitLayoutEffects @ react-dom.development.js:23426
> callCallback @ react-dom.development.js:3945
> invokeGuardedCallbackDev @ react-dom.development.js:3994
> invokeGuardedCallback @ react-dom.development.js:4056
> commitRootImpl @ react-dom.development.js:23151
> unstable_runWithPriority @ scheduler.development.js:646
> runWithPriority$1 @ react-dom.development.js:11276
> commitRoot @ react-dom.development.js:22990
> performSyncWorkOnRoot @ react-dom.development.js:22329
> (anonymous) @ react-dom.development.js:11327
> unstable_runWithPriority @ scheduler.development.js:646
> runWithPriority$1 @ react-dom.development.js:11276
> flushSyncCallbackQueueImpl @ react-dom.development.js:11322
> flushSyncCallbackQueue @ react-dom.development.js:11309
> batchedEventUpdates$1 @ react-dom.development.js:22403
> batchedEventUpdates @ react-dom.development.js:3745
> dispatchEventForPluginEventSystem @ react-dom.development.js:8507
> attemptToDispatchEvent @ react-dom.development.js:6005
> dispatchEvent @ react-dom.development.js:5924

**Comment by AyanBhadury** [comment]
@DevadharshiniN Please import the fusioncharts.overlappedcolumn2d.js file to resolve the problem, here is a demo: https://codesandbox.io/s/overlapped-demo-react-pdfq9
