### ISSUE TITLE
react-fusioncharts doesn't see the FusionCharts license key

### ISSUE THREAD

**Issue by YakimchykNadzeya** [fusioncharts/react-fusioncharts-component#69]
Starting version 3.15.3, FusionCharts uses a newly introduced license. react-fusioncharts doesn't see the license key and doesn't remove a text 'FusionCharts Trial'.

![image](https://user-images.githubusercontent.com/57988716/104157784-2ac6f000-53ec-11eb-93a7-17dff1f7d440.png)

**Comment by AyanBhadury** [comment]
Please drop a mail to support@fusioncharts.com with your license details.
