### ISSUE TITLE
Doesn't support latest version of React (17.0.0)

### ISSUE THREAD

**Issue by scottherlihy** [fusioncharts/react-fusioncharts-component#71]
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-fusioncharts@3.1.2

React 17.0.0 was merged October 20, 2020, but react-fusioncharts still requires old versions.

**Comment by AyanBhadury** [comment]
@scottherlihy The above which you are getting could be npm warnings, react-fusioncharts is compatible with all the versions of react, here is a demo using react v17  :  https://codesandbox.io/s/overlapped-demo-react-pdfq9?file=/package.json
