### ISSUE TITLE
Peer dependency error with react 17.x.x

### ISSUE THREAD

**Issue by jaycho46** [fusioncharts/react-fusioncharts-component#74]
```
> npm i react-fusioncharts

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test-project@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-fusioncharts@3.1.2
npm ERR! node_modules/react-fusioncharts
npm ERR!   react-fusioncharts@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
Npm **error**(not warning) occurs because of peer dependency issue when I run npm install for the first time on a new project.

`npm i --force` can avoid this error but npm still showing few warning messages.

According to this issue #71, there doesn't seem to be any compatibility issues with react 17.
So adding react 17 to the peer dependency shouldn't be a problem.

Please checkout this pr #75

**Comment by jaycho46** [comment]
Please checkout this pr #75

**Comment by Manuel254** [comment]
How can you access the updated react-fusioncharts?

**Comment by jaycho46** [comment]
@Manuel254  This pull request doesn't applied on latest npm release. 
You can use this package temporary before the next official release.
https://www.npmjs.com/package/react-fusioncharts-fix
