### ISSUE TITLE
How to display react gauge using this package?

### ISSUE THREAD

**Issue by santhi-nyros** [fusioncharts/react-fusioncharts-component#8]
Hi, I want to display gauges in reactjs components using this package.
I didn't find the attributes values for gauge like, type. 
**For chart :**
 chartConfigs = {
   type : 'Column3D'
 }
It's working...

**For gauge :** 
chartConfigs = {
   type : 'angulargauge' or 'AngulareGauge'
 }
It's nit working , getting "chart type not supported" error.

Please help me to fix it. Thanks in advance.

**Comment by rousan** [comment]
Hi @santhi-nyros 
You need to import `FusionWidgets` module to render an `AngulareGauge` chart like as follows:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import fusioncharts from 'fusioncharts';
// Load the FusionWidgets module
import Widgets from 'fusioncharts/fusioncharts.widgets';
import ReactFC from 'react-fusioncharts';

// Pass fusioncharts as a dependency
Widgets(FusionCharts)

// Your rest code here

```
